config/routes.rb
Rails.application.routes.draw do
  resources :plays
  get '/play/game' => 'plays#create'
  root to: "home#index"
  authenticated :user do
    root to: "games#index", as: :authenticated_root
  end
  devise_for :managers
  resources :games
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  get "/game/play" => "plays#new"
  resources :managers
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/play.rb
class Play < ApplicationRecord
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new()
    x = request.referrer.to_s
      l = x.split("/")
      puts "="*80
      puts l
      puts "="*80
      i = l[-1].to_i
      @play.game = i
      @play.player = current_user.id
    respond_to do |format|
      if @play.save
        format.html { redirect_to "/games", notice: 'Registrado com sucesso !' }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url, notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/plays/_form.html.erb
<%= form_with(model: play, local: true) do |form| %>
  <% if play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
        <% play.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game %>
    <%= form.number_field :game %>
  </div>

  <div class="field">
    <%= form.label :player %>
    <%= form.number_field :player %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plays/edit.html.erb
<h1>Editing Play</h1>

<%= render 'form', play: @play %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

app/views/plays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plays</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plays.each do |play| %>
      <tr>
        <td><%= play.game %></td>
        <td><%= play.player %></td>
        <%if manager_signed_in?%>
        <%if current_manager.admin%>
        <td><%= link_to 'Show', play %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%end%>
        <%if user_signed_in?%>
        <%if current_user.admin%>
        <td><%= link_to 'Show', play %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if user_signed_in?%>
<%if current_user.admin%>
<%= link_to 'New Play', new_play_path %>
<%end%>
<%end%>
<%if user_signed_in?%>
<%if current_user.admin%>
<%= link_to 'New Play', new_play_path %>
<%end%>
<%end%>

app/views/plays/new.html.erb
<h1>New Play</h1>

<%= render 'form', play: @play %>

<%= link_to 'Back', plays_path %>

app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @play.game %>
</p>

<p>
  <strong>Player:</strong>
  <%= @play.player %>
</p>

<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>