config/routes.rb
Rails.application.routes.draw do
  resources :plays
  get '/play/game' => 'plays#create'
  root to: "home#index"
  authenticated :user do
    root to: "games#index", as: :authenticated_root
  end
  devise_for :managers
  resources :games
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  get "/game/play" => "plays#new"
  resources :managers
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params[:game][:owner]= current_manager.id
      params.require(:game).permit(:place, :date, :price, :size, :owner)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="datetime">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Date</th>
      <th>Price</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.place %></td>
        <td><%= game.date %></td>
        <td><%= game.price %></td>
        <td><%= game.size %></td>
        <%if user_signed_in?%>
        <td><%= link_to 'Play this game', game %></td>
        <% if current_user.admin%>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%end%>
        <%if manager_signed_in?%>
        <% if current_manager.admin%>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if user_signed_in?%>
  <% if current_user.admin%>
    <td><%= link_to 'Users', users_path %></td>
    <br>
    <td><%= link_to 'Managers', managers_path %></td>
    <br>
    <td><%= link_to 'Plays', plays_path %></td>
  <%end%>
<%end%>
<%if manager_signed_in?%>
<%= link_to 'See other players', plays_path %>
<br>
<%= link_to 'New Game', new_game_path %>
<%end%>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @game.place %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @game.size %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @game.owner %>
</p>


<%if user_signed_in?%>
<%if current_user.admin%>
<%= link_to "Users", "/users" %>
<%= link_to "Managers", "/managers" %>
<%end%>

<div class="actions">
<%= button_to 'Play', "/play/game" , method: :get %>
</div>
<%end%>

<%if manager_signed_in?%>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%end%>
<br>
<br>
<%= link_to 'Back', games_path %>